name: proyectos_geo
channels:
  - conda-forge
dependencies:
  - python==3.13.0
  - geopandas==1.0.1
  - gdal==3.10.0
  - tk==8.6.13
  - jinja2==3.1.4
  - numpy==2.1.3
  - pandas==2.2.3
  - matplotlib==3.9.3
  - openpyxl==3.1.5
  - ipywidgets==8.1.5
  - rich==13.9.4
  - pip